# Generated by Django 3.1.3 on 2020-12-12 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteName', models.CharField(max_length=100)),
                ('websiteUrl', models.CharField(max_length=100)),
                ('websiteImage', models.TextField()),
                ('emailSpecial', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('usernameSpecial', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('passwordSpecial', fernet_fields.fields.EncryptedCharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
